### ISSUE TITLE
I can not find the file pom ?

### ISSUE THREAD

**Issue by fanrongqitiancai** [andreaiacono/MapReduce#3]
when I download the project . I can not find the file pom? where  is it? I can not use the maven to resolve package dependencies

**Comment by andreaiacono** [comment]
yep, it wasn't a maven project. Since it was a simple demo, I just added the needed libs to it. 
The libs are:
avro-1.7.6.jar
commons-cli-1.2.jar
commons-lang-2.6.jar
commons-logging-1.1.1.jar
guava-17.0.jar
hadoop-common-2.2.0.jar
hadoop-mapreduce-client-common-2.2.0.jar
hadoop-mapreduce-client-core-2.2.0.jar
hamcrest-core-1.1.jar
jackson-core-2.2.3.jar
javacsv.jar
junit-4.10.jar
log4j-1.2.16.jar
mockito-all-1.8.5.jar
mrunit-1.0.0-hadoop2.jar
